name: Check latest

on:
- push
- workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4
    - name: Git checkout
      run:
        git clone https://git.savannah.gnu.org/git/a2ps.git
    - name: install dependencies
      run:
        sudo apt-get install gperf help2man autopoint libgc-dev
    - name: bootstrap
      run: |
        cd a2ps
        ./bootstrap
    - name: configure
      run: |
        cd a2ps
        ./configure
    - name: build
      run: |
        cd a2ps
        make
    - name: install
      run: |
        cd a2ps
        make install
    - name: verify installation
      run: |
        a2ps --help
