name: Check latest

on:
- push
- workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4
    - name: Git checkout
      run:
        git clone https://git.savannah.gnu.org/git/a2ps.git
    - name: install dependencies
      run:
        sudo apt-get install gperf help2man autopoint libgc-dev libpaper-dev ghostscript recode
    - name: bootstrap
      run: |
        cd a2ps
        ./bootstrap
    - name: configure
      run: |
        cd a2ps
        ./configure
    - name: yacc
      run: |
        cd a2ps/liba2ps
        yacc -d -b parseppd parseppd.y
        cp parseppd.tab.c parseppd.c
        cp parseppd.tab.h parseppd.h
    - name: build
      run: |
        cd a2ps
        make
    - name: install
      run: |
        cd a2ps
        sudo make install
    - name: verify installation
      run: |
        a2ps --help
    - name: create test file
      run: |
        echo "Hello World! äöüßÄÖÜ" > test.txt
        recode -f utf8..latin1 test.txt
    - name: create PS file
      run:
        a2ps -b --center-title="My title" -1 -o test.ps test.txt
      env:
        LANG: de_DE.UTF-8
    - name: create PDF file
      run:
        gs -dSAFER -sPAPERSIZE=a4 -dAutoRotatePages=/None -o test.pdf -sDEVICE=pdfwrite -f test.ps
    - name: upload generated files
      uses: actions/upload-artifact@v4
      with:
        name: files
        path: |
          test.*
